eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://${eureka.instance.hostname}:${server.port}/eureka/}
server:
  port: 8761

spring:
  cloud:
    config:
      enabled: false

